CREATE TABLE chamados
(
    id           NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    setor_id     NUMBER(38, 0),
    titulo       VARCHAR2(255),
    descricao    VARCHAR2(255),
    status       VARCHAR2(255),
    prioridade   VARCHAR2(255),
    data_criacao TIMESTAMP,
    CONSTRAINT pk_chamados PRIMARY KEY (id)
);

CREATE TABLE conteudos_chamado
(
    id              NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    texto           CLOB,
    chamado_id      NUMBER(38, 0)                                  NOT NULL,
    autor_matricula VARCHAR2(255),
    data_criacao    TIMESTAMP,
    caminho_arquivo VARCHAR2(255),
    CONSTRAINT pk_conteudos_chamado PRIMARY KEY (id)
);

CREATE TABLE funcionario
(
    id          NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome        VARCHAR2(255),
    email       VARCHAR2(255),
    cpf         VARCHAR2(255),
    cargo       VARCHAR2(255),
    setor_id    NUMBER(38, 0),
    senha       VARCHAR2(255),
    telefone    VARCHAR2(255),
    logradouro  VARCHAR2(255),
    numero      INTEGER,
    complemento VARCHAR2(255),
    bairro      VARCHAR2(255),
    cidade      VARCHAR2(255),
    estado      VARCHAR2(255),
    cep         VARCHAR2(255),
    CONSTRAINT pk_funcionario PRIMARY KEY (id)
);

CREATE TABLE informativos
(
    id              NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titulo          VARCHAR2(100)                                  NOT NULL,
    conteudo        CLOB      NOT NULL,
    data_publicacao TIMESTAMP NOT NULL,
    ativo           NUMBER(1)                                      NOT NULL,
    CONSTRAINT pk_informativos PRIMARY KEY (id)
);

CREATE TABLE setores
(
    id   NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome VARCHAR2(255),
    CONSTRAINT pk_setores PRIMARY KEY (id)
);

ALTER TABLE funcionario
    ADD CONSTRAINT uc_funcionario_cpf UNIQUE (cpf);

ALTER TABLE chamados
    ADD CONSTRAINT FK_CHAMADOS_ON_SETOR FOREIGN KEY (setor_id) REFERENCES setores (id);

ALTER TABLE conteudos_chamado
    ADD CONSTRAINT FK_CONTEUDOS_CHAMADO_ON_CHAMADO FOREIGN KEY (chamado_id) REFERENCES chamados (id);

ALTER TABLE funcionario
    ADD CONSTRAINT FK_FUNCIONARIO_ON_SETOR FOREIGN KEY (setor_id) REFERENCES setores (id);